### PR TITLE
Use clingo as a submodule

### PR DESCRIPTION
**Pull request by domoritz**
This way we always know which version of clingo was used.

### CODE REVIEW

**Comment by Aluriak** [comment]
Do you want to get full-access to the repo (or ownership) ? You made more things on it than me lately.

**Comment by domoritz** [comment]
Thanks for merging. I would be happy to have full access to the repo. I'm thinking it might even make sense to combine this with https://github.com/domoritz/wasm-clingo into a single repo and move it to the @potassco org. If you give me access to this repo, I will make sure that we have appropriate links. 

@rkaminsk (I just picked you but feel free to redirect me): would you be willing to create a `clingo-wasm` repo in the potassco org and give me access to it?

**Comment by d4hines** [comment]
For what its worth, I'm super excited about using Clingo for production web apps in both browser and NodeJS environments. However, right now the biggest blocker is the poor interface between the JS and WASM environments. I'm very interested in exposing more of the Clingo API via Emscripten, as the example implementation adds huge overhead, and only being able to pass args to stdin via `ccall` is very restrictive.

If we can get faster/more expressive JS interop and an "official" npm module, I think it will be an easier sell to adventurous web developers interested in what the logic paradigm can offer.

**Comment by domoritz** [comment]
Me too! Let's work together. 

I already created an npm module at https://github.com/domoritz/wasm-clingo and use it in other apps. It still requires too much boilerplate to set up but it's a start. 

What do you think about my proposal to consolidate the repos related to clingo wasm and moving it to the potassco org?

**Comment by rkaminsk** [comment]
I think that having a JS API for clingo would be nice. The first step would be to expose the C API we already have via JS. This should just be about changing how things are build. Since the C API is quite low-level, something on top like I did for the Python API would be nice.

I would wait with moving the project to potassco until the project is ready to be used. I won't be contributing much code. JS is not my language and maintaining the Python API is already a lot of work. If there are problems with the build process, I can help.

@tortinator: What do you think?

**Comment by Aluriak** [comment]
@domoritz you have now full access to the repo.

@everyone happy coding !

**Comment by d4hines** [comment]
> What do you think about my proposal to consolidate the repos related to clingo wasm and moving it to the potassco org?

I think that would be fantastic.

@domoritz, investigating the suitability of Clingo for a problem we have it work is one of my top priorities, so I'm quite vested in getting a working JS API.  It would be great if we could organize a todo list of some sort, either in plain text or using Github's built-in project management.

**Comment by tortinator** [comment]
Sounds like a cool idea :) Cheers -t

**Comment by domoritz** [comment]
Excellent. I started a new repo https://github.com/domoritz/clingo-wasm and invited you as collaborators. @d4hines let's create issues in that repo and track progress that way. @rkaminsk I also invited you but I don't expect you to contribute any code. this is just so you can move the repo when we feel it's ready. See you all over there.

**Pull request merged**
