### PR TITLE
Remove debug examples, only support WASM as it’s supported in all mod…

### PR DESCRIPTION
**Pull request by domoritz**
…ern browsers.

### CODE REVIEW

**Comment by Aluriak** [comment]
Thank you for all :)

**Comment by domoritz** [comment]
Couldn't have done it without your starter project. I wonder what your thoughts are on actually publishing the wasm files and making a website available on github pages? 

The potassco website won't update for a while: https://github.com/potassco/potassco.github.io/pull/16.

**Comment by domoritz** [comment]
I'm happy to help review code and give suggestions for web development. Unfortunately, I don't have time for writing a lot of code for other projects. https://vega.github.io/vega-lite/ and https://vega.github.io/editor/#/ keep me quite busy.

**Comment by domoritz** [comment]
@rndmcnlly may be interested in this as well.

**Comment by Aluriak** [comment]
Ok, that's good to know ! Have fun with vega :)

**Comment by domoritz** [comment]
I want to use Clingo on the web so I can run https://github.com/domoritz/draco in the browser. So thank you for all your help!

**Pull request merged**
